# Generated by Django 4.1.4 on 2023-02-04 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LibraryApp', '0002_membermodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssueBookModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_date', models.DateField()),
                ('penalty', models.IntegerField()),
                ('status', models.CharField(max_length=220)),
                ('book', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='LibraryApp.bookmodel')),
                ('member', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='LibraryApp.membermodel')),
            ],
        ),
    ]
