# Generated by Django 4.1.4 on 2023-02-04 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LibraryApp', '0003_issuebookmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issuebookmodel',
            name='issue_date',
        ),
        migrations.RemoveField(
            model_name='issuebookmodel',
            name='penalty',
        ),
    ]
