# Generated by Django 4.1.4 on 2023-02-04 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LibraryApp', '0004_remove_issuebookmodel_issue_date_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IssueBookModel',
            new_name='IssueRequestModel',
        ),
    ]
