# Generated by Django 4.1.4 on 2023-02-04 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LibraryApp', '0005_rename_issuebookmodel_issuerequestmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuerequestmodel',
            name='status',
            field=models.IntegerField(),
        ),
    ]
