# Generated by Django 4.1.4 on 2023-02-04 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LibraryApp', '0006_alter_issuerequestmodel_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuerequestmodel',
            name='status',
            field=models.CharField(max_length=50),
        ),
    ]
