# Generated by Django 4.1.4 on 2023-02-06 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LibraryApp', '0012_penaltymodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PenaltyModel',
        ),
    ]
