# Generated by Django 4.1.4 on 2023-02-16 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LibraryApp', '0017_paymentmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuggestionsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=50)),
                ('suggestion', models.CharField(max_length=250)),
                ('date', models.DateField(auto_now_add=True)),
                ('member', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='LibraryApp.membermodel')),
            ],
        ),
    ]
